name: Tests

on: [push, workflow_dispatch]

jobs:
  Test:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install test dependencies
      run: python -m pip install mypy build

    - name: Build wheel
      run: python -m build

    - name: Install wheel
      run: python -m pip install --no-cache-dir dist/eppidtool-*.whl

    - name: Run MyPy
      run: python -m mypy -p eppidtool

    - name: Run tests
      run: python3 -m unittest discover --verbose